### PR TITLE
[ADD] fields on product seeds and views for months

### PR DESCRIPTION
**Pull request by robinkeunen**
cf: [3 - A1 - Fiche article : web info -> infos variété](https://gestion.coopiteasy.be/web#id=1308&view_type=form&model=project.task&menu_id=338&action=479)

### CODE REVIEW

**Review by remytms — APPROVED** [review]
Great job. :)

Just a end of line in `product_seeds/views/seedling_months.xml`

**Review by remytms — DISMISSED** [review]
I'm wondering if fields shouldn't be named like this :
- `seedling_month_ids`
- `flowering_month_ids`
- …
As there are many2many fields.

What do you think about it ?

**Comment by robinkeunen** [comment]
I don't like `_ids` suffixes but:

> One2Many and Many2Many fields should always have _ids as suffix (example: sale_order_line_ids)

[oca guidlines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#38fields)

**Comment by robinkeunen** [comment]
I also considered refactoring the model `seed.seedming.month` to `seed.month` but I'll do it later (lots of changes).

**Pull request merged**
